services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    # environment:
      # DB_HOST: db
      # DATABASE_URL: postgres://$DB_USER:$DB_PASSWORD@$DB_HOST:$DB_PORT/$DB_NAME
    # depends_on:
      # - db
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json
  # db:
  #   image: postgres:16
  #   restart: always
  #   ports:
  #     - $DB_PORT:5432
  #   environment:
  #     POSTGRES_PASSWORD: $DB_PASSWORD
  #     POSTGRES_USER: $DB_USER
  #     POSTGRES_DB: $DB_NAME
  #   volumes: 
  #     - ./server/db/data:/var/lib/postgresql/data